### ISSUE TITLE
Univeral macOS Binary

### ISSUE THREAD

**Issue by mnightingale** [animetosho/par2cmdline-turbo#10]
Is there any interest in making the macOS binary universal, just might make it a little easier for other tools that depend on it.

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

Only issue I see is maybe there would need to be a macos runner for the lipo tool?

If I take the latest release `lipo -create -output par2 par2x64 par2arm` works 

Combining the dylib in the same way doesn't.

`lipo -create -output libomp libompx64.dylib libomparm.dylib`

> fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: libompx64.dylib and libomparm.dylib have the same architectures (x86_64) and can't be in the same fat output file

Which I thought was strange, it turns out the arm lib already has both. I don't think that was intentional?

```bash
$file libomparm.dylib 
libomparm.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libomparm.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libomparm.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
$ file libompx64.dylib 
libompx64.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

So at the moment if I take `lipo -create -output par2 par2x64 par2arm` and `libomp.dylib` from the arm release it should run on x64 and arm.
Edit: of course I am assuming the x64 bit in the arm dylib is the same as the x64 on its own?
Edit2: but if they do need separate libs the arm one shouldn't have x64 code, then lipo can be ran to combine them

**Comment by mnightingale** [comment]
lipo has a thin option...

`lipo libomparm.dylib -thin arm64 -output libomparm64.dylib` where libomparm.dylib is from the arm64 release.

Then I can `lipo -create -output libomp.dylib libompx64.dylib libomparm64.dylib`

So that should combine what are currently the x64 and arm macOS releases

**Comment by animetosho** [comment]
Thanks for the question. It looks like the `lipo` tool is available on OSXCross, so if both binaries were built via it, it could be possible.

But wouldn't it just be straightforward for someone to do it themselves if they needed a fat binary?

Didn't realise that the supplied libomp has x64 bundled - nice find!  
The next release should have the [OpenMP dependency removed](https://github.com/animetosho/par2cmdline-turbo/pull/9), which should make bundling simpler.
