### ISSUE TITLE
Print SIMD used

### ISSUE THREAD

**Issue by Safihre** [animetosho/par2cmdline-turbo#11]
Could you log somewhere the SIMD acceleration that is being used or that will be used?
When we include this in SABnzbd we need some diagnostic info in case performance is difference then they might expect.
Either due to lacking compiler or due to not-supported hardware.

**Comment by animetosho** [comment]
Adding `-v -v` will print out the primary GF16 kernel chosen, though for how well that represents performance, isn't so straightforward, as there's a bunch of other stuff that can have a significant effect.

If the only concern is around whether SIMD is used at all, the `-v -v` switch is probably good enough.

**Comment by Safihre** [comment]
Yes, maybe it can be part of the `par2 -V` or `par2 -VV` command? 
For regular SABnzbd usage we can't use the verbose log, as it would be too much parsing.
Or `par2 -h`.

**Comment by thezoggy** [comment]
guessing we could prob just do a health check on tools to make sure the version/stuff works as expected..

could do a dummy repair/verify check on something with debug enabled to surface the compute method for this:
`[DEBUG] Compute method: Xor-Jit (SSE2)`

**Comment by Safihre** [comment]
We could, but if it can also be added to a simpler command that would be easier.
Hence this feature request 😊

**Comment by animetosho** [comment]
Selected methods are now displayed with just a single `-v`. I presume this to be good enough?

**Comment by Safihre** [comment]
Thanks!
