### ISSUE TITLE
Debug Synology build failures

### ISSUE THREAD

**Issue by Safihre** [animetosho/par2cmdline-turbo#12]
I tried to get this going on Synology and pushed it through the SynoCommunity pipeline.
As you might remember from `sabctools` some of the platforms use ancient gcc versions (especially the DSM 6.2.4 compilers), so it's a bit exotic. 
But on the other hand, NAS devices are exactly the devices that could benefit from any performance improvements!

I have 1 failure for DSM 7 platform, while others for DSM 7 succeed:
https://github.com/Safihre/spksrc/actions/runs/5574372133/jobs/10182980491#step:6:19641
```
  parpar/gf16/gfmat_coeff.c:13:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
    for (int i = 0; i < 32768; i++) {
    ^
  parpar/gf16/gfmat_coeff.c:13:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
```

All the DSM 6.2 compilers fail with the same log as above and:
https://github.com/Safihre/spksrc/actions/runs/5574372133/jobs/10182980381#step:6:19677
```
  parpar/gf16/gf16mul.cpp: In static member function 'static Galois16Methods Galois16Mul::default_method(size_t, unsigned int)':
  parpar/gf16/gf16mul.cpp:1222:8: error: 'CpuCap' does not name a type
```

**Comment by Safihre** [comment]
I forced `-std=c11` and now getting some more successes but also different failures, even for jobs that succeeded before (like x64-7.1). 
Surprised it could have negative side-effects to add this extra flag.
https://github.com/Safihre/spksrc/actions/runs/5575011275/jobs/10184437167#step:6:19604

**Comment by animetosho** [comment]
Thanks for finding those!

Could you retry them with the latest changes?

**Comment by Safihre** [comment]
It improved things!
Now only left with the C++11 errors.
Might be needed to fix it on `spksrc` side by forcing the `-std=c11` flag for older gcc's, although always confused which flag to add it to (`CF/CPP/CXX`).
https://github.com/Safihre/spksrc/actions/runs/5576692083/jobs/10188476658#step:6:19605

**Comment by animetosho** [comment]
Thanks for trying that again.

I'm not sure what the correct fix is for the missing mmap flags, so have put in an experiment.

C++11 support is required so this won't build with C++03. I've added some detection via automake - see if that helps.

**Comment by Safihre** [comment]
Ah I used https://github.com/animetosho/par2cmdline-turbo/commit/a7e21d81742069e68be9f48e7206f3661a408c53 since it was linked to this issue.
I can try the latest one.
