### ISSUE TITLE
macOS arm release much slimmer than x86 one

### ISSUE THREAD

**Issue by Safihre** [animetosho/par2cmdline-turbo#16]
I was adding par2cmdline-turbo to our macOS release and noticed that the (unpacked) par2 for arm is only 700kb while the one for x86 is 1700kb.
It's not a huge difference on our already heavy SABnzbd release, but still.
Would it be worth it to strip the release binaries?

**Comment by animetosho** [comment]
I thought the build was already stripped, but it seems like none of the MacOS binaries are.  
Stripping the x86 binary drops it from 1646KB to 1590KB, so not a huge saving, but it's something I suppose.

The x86 builds having [a lot more kernels](https://github.com/animetosho/ParPar/blob/01b21ab295d20594309b6e4bac465ed746e94876/help.txt#L270-L288) than the ARM builds, could be contributing to the size difference. I can look at trimming down some of the less useful kernels in future builds.

**Comment by Safihre** [comment]
Oh in that case it doesn't matter 👍 thought it might make a a lot more difference!
