### ISSUE TITLE
Could not open source file with unicode path/file name when verifing

### ISSUE THREAD

**Issue by chinagaofeng** [animetosho/par2cmdline-turbo#17]
the source file name has unicode chars. Verifing with multipar(parj64) is success, but par2cmdline-turbo failed

![screen](https://github.com/animetosho/par2cmdline-turbo/assets/30225503/00fa426d-6a56-4275-96c9-a100bd5b3099)

**Comment by animetosho** [comment]
This sounds like a similar issue to #13

Please retry with the [original par2cmdline](https://github.com/Parchive/par2cmdline) - if the issue persists, please [report the issue there](https://github.com/Parchive/par2cmdline/issues/new).

I don't think par2cmdline has any special handling for names with non-ASCII characters. Unfortunately, it seems like Windows requires use of a different API for it to work correctly.

**Comment by Safihre** [comment]
Openend the issue with upstream.
