### ISSUE TITLE
'make' fails on Debian 11

### ISSUE THREAD

**Issue by ICE-COOL-LEMONADE** [animetosho/par2cmdline-turbo#21]
when using the turbo branch the make process fails
```
make[1]: *** [Makefile:2404: parpar/gf16/libparpar_gf16_sse2_a-gf16_xor_sse2.o] Error 1
make[1]: Leaving directory '/home/ICL/bin/par2cmdline-turbo'
make: *** [Makefile:1252: all] Error 2
```

the older master branch configures & makes successfully

**Comment by animetosho** [comment]
Oops, can you try again with the latest code?

If it still fails, could you post a longer log?

**Comment by ICE-COOL-LEMONADE** [comment]
all working now :)
