### ISSUE TITLE
Create new release?

### ISSUE THREAD

**Issue by Safihre** [animetosho/par2cmdline-turbo#24]
Maybe you could create a new release with all the patches? Then I can refer to that officially :)

**Comment by animetosho** [comment]
There hasn't been many changes since the last release.  
Were you just interested in the build fixes for niche platforms?

**Comment by Safihre** [comment]
Yeah so maybe just a 1.1.1 release I thought?

**Comment by animetosho** [comment]
Released v1.1.1.

**Comment by Safihre** [comment]
Thank you!

**Comment by thezoggy** [comment]
just to note, updated tests with par2cmdline-turbo 1.1.1 
https://gist.github.com/thezoggy/3c243b712f0cc960fa4dd78ff1ab56e7

as expected not much change since 1.0.1 in terms of performance.
did see my nas box that uses amd x64 cpu method go from `Xor-Jit (AVX2)` to `Shuffle (AVX2)`

**Comment by animetosho** [comment]
Thanks for the tests. My guess is that your test doesn't have enough bad blocks to judge subtle perf differences, so I'm not expecting any notable improvements in the future.

> did see my nas box that uses amd x64 cpu method go from Xor-Jit (AVX2) to Shuffle (AVX2)

That's unexpected. There's a new "Inversion method" that's listed - are you sure you're not picking that over "Multiply method"?

Also M1 Macs should prefer `CLMul (SHA3)` now; I wonder if it's just not being detected...

**Comment by thezoggy** [comment]
> Thanks for the tests. My guess is that your test doesn't have enough bad blocks to judge subtle perf differences, so I'm not expecting any notable improvements in the future.
> 
> > did see my nas box that uses amd x64 cpu method go from Xor-Jit (AVX2) to Shuffle (AVX2)
> 
> That's unexpected. There's a new "Inversion method" that's listed - are you sure you're not picking that over "Multiply method"?
> 
> Also M1 Macs should prefer `CLMul (SHA3)` now; I wonder if it's just not being detected...

Indeed `Inversion method:` is what I used on this latest test as Compute method wasnt there anymore..

looks like what was Compute method is now the "Multiply method". 
Guess i need to redo my tests to denote the correct field, should I include both (dunno if inversion method changes/means much).

on my amd x64 box, 
```
Computing Reed Solomon matrix.
Construction accel: AVX2
Inversion method: Shuffle (AVX2)
Constructing: done.
Solving: done.

Multiply method: Xor-Jit (AVX2)
```

**Comment by animetosho** [comment]
Yeah sorry for the name change - I thought it'd be necessary if more methods were being displayed.  
Inversion method will almost always be the same as Multiply method, the only difference being that inversion may avoid using Xor-Jit.

I don't expect inversion to be notable for typical scenarios. It only matters if there's a large number of damaged blocks (like >1000).  
The hashing methods are what's using during verification.

It looks like the supplied MacOS binaries lack the `CLMul (SHA3)` kernel for some reason. I'll investigate why.

**Comment by thezoggy** [comment]
redoing some tests right now, updating: https://gist.github.com/thezoggy/3c243b712f0cc960fa4dd78ff1ab56e7

**Comment by thezoggy** [comment]
testing mac m1 release from https://github.com/animetosho/par2cmdline-turbo/actions/runs/7362627412

can see inv/mul method went from `CLMul (NEON)` to `CLMul (SHA3)` as expected
```
Repair is required.
19 file(s) exist but are damaged.
22 file(s) are ok.
You have 5584 out of 5611 data blocks available.
You have 791 recovery blocks available.
Repair is possible.
You have an excess of 764 recovery blocks.
27 recovery blocks will be used to repair.

Computing Reed Solomon matrix.
Construction accel: NEON
Inversion method: CLMul (SHA3)
Constructing: done.
Solving: done.

Multiply method: CLMul (SHA3)
```
made repair slightly faster, 4s->3s but of course with variance on such a small data set is hard to see when its already so darn quick :)

i did notice that the par2 binary did just about double in size, both came from github
par2 = from 1.1.1
```
-rwxrwxrwx  1 zog  user   593K Dec  5 22:53 par2
-rwxr-xr-x@ 1 zog  user   945K Dec 30 14:14 par2-dev
```

**Comment by animetosho** [comment]
Ooh, thanks for trying that out. So it looks like the issue was because the v1.1.1 build was done on an older compiler.

Yeah I don't think your data set is large enough to see much of a difference. The additional kernel does mean more code is included, though I kept debug symbols for that build, so that might contribute a little to the size.  
I think M1 is the oldest ARM chip that MacOS supports? If that's the case, the `CLMul (NEON)` kernel could get stripped out for MacOS builds.

**Comment by thezoggy** [comment]
Wonder if it's mainly just the symbols vs that code. Dunno if there is any risk on not including neon, especially when you prob would include it for mac x86 binary.. which might be used on a m1 Mac.

**Comment by animetosho** [comment]
NEON is ARM only, so won't be present in x86 binaries.

I do recall now that Apple made some MacOS dev kits(?) with their A12Z CPU, so I guess M1 isn't the oldest ARM chip MacOS supports. The A12Z doesn't support the SHA3 extension, so I'll probably keep the NEON variant.  
I don't see Hackintoshes or similar, so that likely won't be a concern.
