### ISSUE TITLE
new release - updates

### ISSUE THREAD

**Issue by thezoggy** [animetosho/par2cmdline-turbo#26]
i saw the memory fixes you made this morning, curious if you think its worth tagging an updated release or if prob not affecting most people (need x86 build and set to use large memory to hit out of bounds)?

btw I saw this recently and thought you might be interested for one of your projects:
https://www.phoronix.com/news/x86-simd-sort-5.0
-- https://github.com/intel/x86-simd-sort/

**Comment by animetosho** [comment]
It doesn't sound like a common issue from the reports received so far, so I'm not feeling rushed to tag a release just for that.

Sorting isn't really an issue for PAR2, but thanks for the info regardless!

**Comment by thezoggy** [comment]
Saw this announced, figure you might be interested:
https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by animetosho** [comment]
Thanks for the info! Have been using the MacOS ARM instances for testing, but nice to see Linux and particularly Windows options available too.

> We expect to begin offering Arm runners for open source projects by the end of the year.

Okay, so it's still a few months off. Could be useful for testing Windows ARM when that arrives.

**Comment by animetosho** [comment]
v1.2.0 has now been released with the changes.
