### ISSUE TITLE
`par2cmdline-turbo` as Python package

### ISSUE THREAD

**Issue by brenthuisman** [animetosho/par2cmdline-turbo#29]
I wrapped this excellent project up as an installable Python package, so that I can use it as a dependency for `par2deep`. I hope that's OK, and if you'd like me to merge this back or have the package name that'd be OK. As long as the package can stay ;)

- https://github.com/brenthuisman/par2cmdline-turbo.py
- https://pypi.org/project/par2cmdline-turbo

**Comment by brenthuisman** [comment]
Also, I haven't tested on all platforms. If anyone can confirm all works fine, that'd be great feedback.

**Comment by thezoggy** [comment]
seems like its going to get confusing to people by saying your not affiliated with par2cmdline-turbo but named it the same name and having people do `$ pip install par2cmdline-turbo`

perhaps a name change to avoid the confusion?

**Comment by brenthuisman** [comment]
O, I thought it makes sense since they're the same binaries. It works (almost) the same for `hugo` on PyPI.

But if it bothers you and you don't wish to have the package here, sure, I can rename it. What would be not confusing? A totally new name might seem like taking credit for something that is not even related but the same binary.

**Comment by thezoggy** [comment]
Maybe I'm missing the point of this, but this is just installing the package? Why would you use this instead of your package manager?

**Comment by brenthuisman** [comment]
For some software, `pip` is the package manager. Just like for some it is pacman, dnf, etc.

**Comment by animetosho** [comment]
Never thought of putting it in the pip repo, but if it makes sense to you, I have no qualms about it.

Thanks for the contribution!
