### ISSUE TITLE
Create Windows ZIP or EXE releases for WinGet & add Homebrew 

### ISSUE THREAD

**Issue by mcexit** [animetosho/par2cmdline-turbo#30]
I'd like to be able to create a [WinGet](https://learn.microsoft.com/windows/package-manager/winget/) manifest for this app, but unfortunately the Windows Package Manager [doesn't support](https://github.com/microsoft/winget-cli/issues/2899) installing apps from other archive file formats yet at this time. I'm only interested in creating a local package at this time for my personal use, but if you'd like to have it added to the [official manifest repo](https://github.com/microsoft/winget-pkgs) then please let me know.

I'd also like to see if you'd like the app packaged for [Homebrew](https://brew.sh) (the macOS package manager)? Again, if so let me know. [Here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/p/par2.rb) is an example of what a Homebrew formulae (manifest) looks like for the official par2cmdline.

**Comment by animetosho** [comment]
Thanks for the info. If I understand you correctly, you just want ZIP packages in the Releases section?

I'm happy for you to package this up in any way you like.

**Comment by animetosho** [comment]
Got it, build script updated to produce ZIP packages.
