### ISSUE TITLE
provide a pre-built linux-riscv64 version?

### ISSUE THREAD

**Issue by sanderjo** [animetosho/par2cmdline-turbo#33]
Is it possible for you to provide a pre-built linux-riscv64 version? So `par2cmdline-turbo-v1.1.1-linux-riscv64.xz` or `par2cmdline-turbo-v1.1.2-linux-riscv64.xz`

That would save quite some hassle & time in my docker image building

![image](https://github.com/user-attachments/assets/7a860835-5f63-46b6-b764-beb0d6b40650)

**Comment by animetosho** [comment]
RISC-V support is still considered experimental. It often requires building with bleeding edge compilers, and I'm not sure how stable the environment is in general (e.g. what profile to build for).

I'm providing RVV code for those interested, but it has little popularity at the moment.  
For now, I'm thinking of holding back on RISC-V binaries until the environment becomes more developed and more widely adopted.

(similar with #31 as I'm not really prioritising RV releases)

**Comment by sanderjo** [comment]
OK, clear, still experimental.
