### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ErrorNoInternet** [animetosho/par2cmdline-turbo#7]
I have 2 files:
```
$ wc -c *
 8088809375 serror-backups_001.tar.zst
79458498446 serror-backups_002.tar.zst
87547307821 total
```

When I try to create a par2 archive using `par2 c -v -abackup -r5 -m16384 *` (5% redundancy), it gets stuck at:
```
Block size: 43778788
Source file count: 2
Source block count: 2000
Recovery block count: 100
Recovery file count: 7

Opening: serror-backups_001.tar.zst
Opening: serror-backups_002.tar.zst
Processing: 0.5%
```
for a few seconds, and then segfaults.
This seems to happen with anything larger than 5% redundancy as well.

However, when I do 3% redundancy:
```
Block size: 43778788
Source file count: 2
Source block count: 2000
Recovery block count: 60
Recovery file count: 6

Opening: serror-backups_001.tar.zst
Opening: serror-backups_002.tar.zst
Wrote 2626727280 bytes to disk                                                                                                                       
Writing recovery packets
Writing verification packets
Done
```
it works perfectly fine.
1%-4% is fine, 5%+ segfaults.

This doesn't seem to happen with the original par2cmdline (5% redundancy):
```
Block size: 43778788
Source file count: 2
Source block count: 2000
Recovery block count: 100
Recovery file count: 7

Opening: serror-backups_001.tar.zst
Opening: serror-backups_002.tar.zst
Computing Reed Solomon matrix.
Constructing: done.
Proocessing: 1.0%
```

[coredump.txt](https://github.com/animetosho/par2cmdline-turbo/files/11561355/coredump.txt)

**Comment by animetosho** [comment]
Thanks for the detailed report!

I found a bug, which I think is the one you're experiencing. Would you be able to test the latest Git code with this fix?

**Comment by ErrorNoInternet** [comment]
Yup, that has fixed it!

Thank you so much for working on this project. It has really helped me a lot, and saved me a ton of time.
